name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: sudo apt-get install libexpected-dev libgtest-dev libbenchmark-dev cmake clang-tidy clang-format doxygen ninja-build python3 python3-venv libgmock-dev

    - name: Initialisation
      run: |
        make docs-init
        . venv/bin/activate
        make init

    - name: Build Tests
      run: make build-test

    - name: Execute Tests
      run: make exec-test
