name: Install

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Initialisation
      run: make init

    - name: Build Tests
      run: make build-test

    - name: Execute Tests
      run: make exec-test|
