name: Documentation

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install doxygen
        run: sudo apt-get install python

      - name: Build
        run: make docs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/build
