name: Style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install clang-format
      run: sudo apt-get install clang-format clang-tidy

    - name: configure
      run: make init

    - name: check style
      run: make check-format

    - name: check linting
      run: make lint
